Add ContainsHeader method to check custom header presence
naighes/Carrot pull request #23
Opened 2018-10-27 18:54 UTC by lbragaglia

Adds a ContainsHeader to HeaderCollection and also to container message classes, i. e. consumed and outbound message (resolves #22).

2018-11-02 07:43 UTC, naighes requested changes
Looks fine!
We're used to keep close to [.NET built'in types](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/built-in-types-table) and aliasing is "discouraged".
Please, have a look to my suggestions.

Thanks!

2018-11-02 07:43 UTC, naighes commented on src/Carrot.Tests/OutboundEnveloping.cs
> +            const string key = "a";
```suggestion
            const String key = "a";
```

2018-11-02 07:43 UTC, naighes commented on src/Carrot.Tests/OutboundEnveloping.cs
> +            const string value = "b";
```suggestion
            const String value = "b";
```

2018-11-02 07:43 UTC, naighes commented on src/Carrot/Messages/Message.cs
> +        public bool ContainsHeader(String key) => Headers.ContainsHeader(key);
```suggestion
        public Boolean ContainsHeader(String key) => Headers.ContainsHeader(key);
```

2018-11-05 12:20 UTC, lbragaglia commented
Please let me know if you prefer squashing into one commit before merging.

2018-11-08 07:58 UTC, naighes commented
> Please let me know if you prefer squashing into one commit before merging.
Yeah, that'd be great!

2018-11-08 14:50 UTC, merged